export const ENDPOINTS = {
  LOGIN: "/auth/login",
  CHECK_ROLE: "/auth/role",
  LOGOUT: "/auth/logout",
  PROFILE: "/profile",
  UPLOAD_IMAGE: "/profile/upload-image",
  // PROFILE_IMAGE: "/profile/image",
  CHANGE_PASSWORD_REQUEST: "/profile/change-password/request",
  CHANGE_PASSWORD_VERIFY: "/profile/change-password/verify",
  FRANCHISE: "/franchise",
  USERS: "/rbac/users",
  ROLES: "/rbac/roles",
  WALLET: "/wallet/transactions",
  REMITTANCE: "/remittance",
  INVOICES: "/invoices",
  CONSIGNEES: "/orders/consignees",
  ORDERS: "/orders",
  SCAN_ORDER: "/orders/scan",
  GET_ORDER_PINCODE: "/orders/get-pincode",
  TODAY_STATUS: "/orders/orders/today-status",
  ACTIVITY_LOGS: "/activity-logs",
  WAREHOUSE: "/warehouse",
  SERVICE_REVIEWS: "/project/reviews",
  ORDER_REVIEWS: "/product-reviews",
  BULK_ORDER_UPLOAD: "/orders/bulk",
  NOTIFICATIONS_WS: "/websocket/ws/notifications",
  READ_NOTIFICATION: (id) => `/notifications/${id}/read`,
  RATE_CALCULATOR: "/rate-calculator/calculate",

};
